### PR TITLE
Bugfix / 121 / Implement UUID in sprites

### PR DESCRIPTION
**Pull request by The0mikkel**
Fixed a minor bug, where sprites where only cached based on their texture.

### CODE REVIEW

**Review by JfriisJ — APPROVED** [review]

**Review by Muhammed-als — APPROVED** [review]
LGTM!

**Review by jakob753951 — APPROVED** [review]
LGTM

**Comment by AnneLaerke** [comment]
Beautifully executed

**Review by AnneLaerke — APPROVED** [review]
Very nice, very approvable now 👍

**Pull request merged**
